---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# mypkg

<!-- badges: start -->
<!-- badges: end -->

The goal of mypkg is to ...

## Installation

You can install the development version of mypkg like so:

Clone the repository and open the .Rproj file in RStudio.

Then run:

``` r
library(devtools)
install()
```

## Set-up

```{r setup, eval = FALSE}
library(mypkg)

# Configure virtual environment
venv_info = mypkg_config()
venv = venv_info$hash
print(venv)
# [1] "a9c268bc"

# Do the python deps load?
library(reticulate)
np = import("numpy", convert = FALSE)
lasso_mod = import("selectinf.randomized.lasso", convert = FALSE)$lasso
py_get_attr(selectinf$randomized$lasso, "__file__")
# Simple test
run_simple_lasso_test_snigdha_fixed(venv)
```

## Or, if already configured, use 

```{r}
library(mypkg)
library(reticulate)
use_virtualenv("a9c268bc", required = TRUE)
np = import("numpy", convert = FALSE)
lassopy = import("selectinf.randomized.lasso", convert = FALSE)$lasso
# selected_targets = import("selectinf.base", convert = FALSE)$selected_targets  
const = lassopy$gaussian
exact_grid_inference = import("selectinf.randomized.exact_reference", convert = FALSE)$exact_grid_inference  

```

